@echo off
echo Pobieranie Pythona...
curl -o python_installer.exe https://www.python.org/ftp/python/3.10.0/python-3.10.0-amd64.exe
echo Instalowanie Pythona...
python_installer.exe /quiet InstallAllUsers=1 PrependPath=1 Include_test=0
echo Instalowanie Pytube...
python -m pip install pytube
echo Pobieranie YtDonwloader.py...
curl -o YtDonwloader.py https://gist.githubusercontent.com/TechAdrianPro/8ab9a1a93a1a32631b01abb26f6b16bc/raw/9a0c03d478300c6c32ba6ae4e11a42f79adbb3b7/YtDonwloader.py
echo Gotowe!
echo Otwieranie pliku YtDonwloader.py...
python YtDonwloader.py
